In [1]:
import numpy as np
observations = 1000

In [2]:
xs=np.random.uniform(low=-10,high=10,size=(observations,1))
zs=np.random.uniform(low=-10,high=10,size=(observations,1))
inputs=np.column_stack((xs,zs))

In [3]:
inputs

array([[-0.04937765, -4.00842835],
       [-6.69396279, -5.20716676],
       [ 1.14689928,  5.21716681],
       ...,
       [ 5.03265618,  1.4944305 ],
       [ 6.24634126, -1.33752914],
       [-7.90107698,  2.16430785]])

In [4]:
#lets assume arbitrary target function 7*xs-4*zs+3+noise
noise=np.random.uniform(low=-1,high=1,size=(observations,1))
targets = 7*xs - 2 *zs + 6 + noise
#targets = 1000 x 1
#xs = 1000 x 1
#zs = 1000 x 1
#noise = 1000 x 1

In [5]:
targets

array([[ 12.69715581],
       [-30.32656151],
       [  3.17383008],
       [ 13.90492968],
       [ -2.13027535],
       [-36.45833733],
       [ 60.97514256],
       [-37.13465712],
       [ 37.93601149],
       [ 47.99679816],
       [-32.16665585],
       [-36.01700968],
       [ 36.83409263],
       [ 30.306391  ],
       [ 35.73536206],
       [-39.79980943],
       [-15.57474549],
       [ 50.92992412],
       [ 63.45825576],
       [ 29.32371115],
       [ 35.82683191],
       [ 50.13754174],
       [-26.22381304],
       [ 22.14350009],
       [ -1.8232944 ],
       [  4.97370486],
       [ 91.11270368],
       [-17.97808509],
       [-31.93732433],
       [-17.4335229 ],
       [  6.85112223],
       [ 92.25875293],
       [ 28.71953831],
       [  7.159519  ],
       [ 21.73969929],
       [ 29.80781581],
       [ 87.10415855],
       [ -4.83705364],
       [-44.6530826 ],
       [-34.32335571],
       [ 30.73963145],
       [ 69.72118303],
       [ 84.33264961],
       [-21

In [6]:
init_range=0.1
weights=np.random.uniform(-init_range,init_range,size=(2,1))
biases=np.random.uniform(-init_range,init_range,size=1)

In [7]:
biases

array([-0.02665948])

In [8]:
learning_rate = 0.02

In [9]:
outputs = np.dot(inputs,weights) + biases

In [10]:
outputs

array([[-1.37543602e-01],
       [ 3.66787649e-01],
       [ 2.98906961e-02],
       [-1.02402681e-01],
       [ 5.06327310e-02],
       [ 5.14253585e-01],
       [-7.05646978e-01],
       [ 4.44243907e-01],
       [-3.64237427e-01],
       [-4.81628981e-01],
       [ 3.76945622e-01],
       [ 4.39976020e-01],
       [-3.51452817e-01],
       [-2.86283898e-01],
       [-3.36751754e-01],
       [ 5.16166050e-01],
       [ 2.23602888e-01],
       [-5.70985876e-01],
       [-6.70278303e-01],
       [-3.15351841e-01],
       [-4.11743303e-01],
       [-4.95414136e-01],
       [ 3.33563239e-01],
       [-2.41311575e-01],
       [ 1.15430391e-01],
       [ 2.31633747e-02],
       [-1.04599914e+00],
       [ 2.42846906e-01],
       [ 4.69110481e-01],
       [ 2.91830818e-01],
       [-7.54652930e-02],
       [-1.08621218e+00],
       [-2.53181216e-01],
       [ 4.90011505e-03],
       [-2.11276492e-01],
       [-3.12335112e-01],
       [-1.00898612e+00],
       [ 5.11040637e-02],
       [ 5.4

In [12]:
for i in range(200):
    outputs = np.dot(inputs,weights) + biases
    deltas = outputs - targets
    loss = np.sum(deltas**2)/2/observations
    print(loss)
    deltas_scaled=deltas/observations
    #print(deltas)
    #print(deltas_scaled)
    #print("inputs:{} deltas_scaled:{}".format(inputs.shape,deltas_scaled.shape))
    weights = weights - learning_rate * np.dot(inputs.T,deltas_scaled)
    biases = biases - learning_rate * np.sum(deltas_scaled)
print(weights,biases)

0.17327880320671835
0.17305429283524532
0.17283863790788723
0.17263148913614598
0.17243251100863677
0.1722413812476714
0.1720577902872787
0.17188144077180958
0.17171204707432178
0.17154933483396115
0.17139304051158769
0.17124291096293126
0.1710987030285833
0.17096018314016068
0.17082712694200158
0.17069931892778714
0.17057655209149228
0.17045862759210523
0.17034535443157311
0.17023654914544772
0.17013203550573688
0.17003164423547232
0.16993521273453893
0.16984258481631662
0.16975361045471163
0.16966814554116316
0.1695860516512372
0.16950719582042512
0.16943145032878462
0.16935869249407873
0.16928880447306976
0.16922167307065417
0.16915718955652329
0.16909524948905819
0.16903575254616807
0.16897860236280338
0.16892370637487591
0.1688709756693361
0.16882032484016452
0.16877167185004224
0.16872493789747836
0.16868004728917715
0.16863692731744181
0.1685955081424109
0.16855572267894256
0.16851750648795827
0.16848079767207355
0.1684455367753448
0.16841166668697133
0.1683791325487936
0.168347